[package]
name = "ebms-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ebms-app"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ebms-core = { path = "../crates/ebms-core" }
dirs.workspace = true
futures-util.workspace = true
open.workspace = true
serde.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ebms-vfs-fuse = { path = "../crates/ebms-vfs-fuse" }

[target.'cfg(windows)'.dependencies]
ebms-vfs-winfsp = { path = "../crates/ebms-vfs-winfsp" }
